import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "./layout.module.css";
import { Stack } from "@mui/material";

function Layout({ children, ...props }) {
  const router = useRouter();
  return (
    <div className={styles.container} {...props}>
      <Head>
        <title>DevNeeds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        className={styles.nav}
        direction="row"
        alignItems="center"
        justifyContent="space-between"
        sx={{ "& a": { color: props.color } }}
      >
        <Link href="/">
          <a>
            <h1 className={styles.title}>DevNeeds</h1>
          </a>
        </Link>
        <ul className={styles.navLinks}>
          <li className={router.pathname == "/" ? styles.active : ""}>
            <Link href="/">Board</Link>
          </li>
          <li className={router.pathname == "/colors" ? styles.active : ""}>
            <Link href="/colors">Colors</Link>
          </li>
          <li className={router.pathname == "/glass" ? styles.active : ""}>
            <Link href="/glass">Glass</Link>
          </li>
          <li className={router.pathname == "/gradient" ? styles.active : ""}>
            <Link href="/gradient">Gradient</Link>
          </li>
          <li className={router.pathname == "/neo" ? styles.active : ""}>
            <Link href="/neo">Neo</Link>
          </li>

          <li className={router.pathname == "/shadow" ? styles.active : ""}>
            <Link href="/shadow">Shadow</Link>
          </li>
        </ul>
      </Stack>
      <main className={styles.main}>{children}</main>
    </div>
  );
}

export default Layout;
