import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "./layout.module.css";
import { Box, IconButton, Stack } from "@mui/material";
import MenuIcon from "@mui/icons-material/Menu";
import * as React from "react";
import Drawer from "@mui/material/Drawer";
import Button from "@mui/material/Button";
import { invertColor } from "../functions";
import NavLinks from "./NavLinks";

function Layout({ children, ...props }) {
  const router = useRouter();
  const [state, setState] = React.useState({
    top: false,
    left: false,
    bottom: false,
    right: false,
  });

  const toggleDrawer = (anchor, open) => (event) => {
    if (
      event.type === "keydown" &&
      (event.key === "Tab" || event.key === "Shift")
    ) {
      return;
    }

    setState({ ...state, [anchor]: open });
  };
  const anchor = "right";

  return (
    <div className={styles.container} {...props}>
      <Head>
        <title>DevNeeds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        className={styles.nav}
        direction="row"
        alignItems="center"
        justifyContent="space-between"
        sx={{ "& a": { color: props.color } }}
      >
        <Link href="/">
          <a>
            <h1 className={styles.title}>DevNeeds</h1>
          </a>
        </Link>
        <Box sx={{ display: { xs: "none", lg: "block" } }}>
          <NavLinks router={router}></NavLinks>
        </Box>
        <IconButton
          onClick={toggleDrawer("right", true)}
          sx={{ display: { sx: "block", lg: "none" } }}
        >
          <MenuIcon
            sx={{
              color: props.color ? props.color : "white",
            }}
          />
        </IconButton>
      </Stack>
      <React.Fragment>
        <Drawer
          anchor="right"
          open={state["right"]}
          onClose={toggleDrawer("right", false)}
        >
          <Box
            sx={{
              width: anchor === "top" || anchor === "bottom" ? "auto" : 250,
              padding: "10px",
              height: "100%",
              "& a": { color: props.color ? props.color : "white" },
              "& li": { marginBottom: "10px" },
              backgroundColor: props.color
                ? invertColor(props.color)
                : "rgba(22, 22, 22, 1)",
            }}
            role="presentation"
            onClick={toggleDrawer(anchor, false)}
            onKeyDown={toggleDrawer(anchor, false)}
          >
            <NavLinks router={router} style={{ display: "block" }}></NavLinks>
          </Box>
        </Drawer>
      </React.Fragment>
      <main className={styles.main}>{children}</main>
    </div>
  );
}

export default Layout;
